import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Commands from "../components/Commands";
import DroneState from "../components/DroneState";

const Home: NextPage = () => {
  const travelDistance = 20;

  return (
    <div className={styles.container}>
      <Head>
        <title>Bison drone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.container}>
        <h1 className={styles.title}>Awesome Bison drone</h1>
        <img src="/bison.png" alt="bison logo" className={styles.image} />
        <Commands travelDistance={travelDistance} />
        <DroneState travelDistance={travelDistance} />
      </main>
    </div>
  );
};

export default Home;
