import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Commands from "../components/Commands";
import DroneState from "../components/DroneState";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Awesome Bison drone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Bison drone</h1>
        <Commands />
        <DroneState />
      </main>
    </div>
  );
};

export default Home;
